set(_CATKIN_CURRENT_PACKAGE "merge_lasers")
set(merge_lasers_MAINTAINER "Audeliano Wolian Li <audeliano@gmail.com>")
set(merge_lasers_DEPRECATED "")
set(merge_lasers_VERSION "0.0.0")
set(merge_lasers_BUILD_DEPENDS "geometry_msgs" "sensor_msgs" "roscpp")
set(merge_lasers_RUN_DEPENDS "geometry_msgs" "sensor_msgs" "roscpp")
set(merge_lasers_BUILDTOOL_DEPENDS "catkin")